#!/usr/bin/python

import os, sh, io, json, itertools as it

def mean(L): return sum(L) / len(L) if L else 0
sensors = json.load(io.BytesIO(sh.sensors('-j').stdout))
relevant = os.environ.get('BLOCK_INSTANCE', ';'.join(sensors.keys())).split(';')
temp = mean([
  value
  for sensor, metadata in sensors.items()
  for name, readings in metadata.items()
  if name !=' Adapter' and any(it.chain(
    (sensor in relevant, metadata['Adapter'] in relevant),
    (name.startswith(r) for r in relevant),
  ))
  for reading, value in (readings if type(readings) == dict else {}).items()
  if reading.endswith('_input')
])
print(f" {temp:.1f} °C")
print(f" {temp:.1f} °C")
print("")