#!/usr/bin/env bash

INSTANCE="${BLOCK_INSTANCE}"

# Usage:
#  CPU;10;8  (top 10 cpu proc, 8 spaces max)
#  MEM;5;8  (top 5 mem proc, 8 spaces max)

FIELD=$(echo "${INSTANCE}" | awk -F ';' '{print $1}')
N_TOP=$(echo "${INSTANCE}" | awk -F ';' '{print $2}')
FIELD_MAX_WIDTH=$(echo "${INSTANCE}" | awk -F ';' '{print $3}')

# Field special specifiers
if [ "${FIELD}" == "CPU" ]; then
  FIELD=3
elif [ "${FIELD}" == "MEM" ]; then
  FIELD=4
fi

OUT=$( \
  ps aux \
    | awk "NR>1{print \$${FIELD}, \$11}" \
    | sort -rk1 \
    | uniq -uf1 \
    | head -n ${N_TOP} \
    | awk "{
  if(NR>1) {
    printf(\" \");
  }
  VAL=\$1;
  RC=(VAL/100)*255;
  GC=255-RC;
  BC=0;
  split(\$2, NAME_PART, \"/\");
  NAME=NAME_PART[length(NAME_PART)];
  printf(\"<span foreground=\\\"#%0.2x%0.2x%0.2x\\\">%6.2f</span> %-${FIELD_MAX_WIDTH}.${FIELD_MAX_WIDTH}s\", RC, GC, BC, VAL, NAME);
}")
pre
echo "${OUT}"
echo "${OUT}"
echo ""
